### ISSUE TITLE
getting firebase_messaging token in addition to apns token

### ISSUE THREAD

**Issue by fvisticot** [mwaylabs/flutter-apns#17]
I would like to use the apns token to use my own server to send push notifications. 
But in addition, i would like to send firebase push notification for other "marketing" push notification.
Do you think it would be possible to provide both tokens in case of iOS platform (apns + firebase) ?

**Comment by RafaelPlantard** [comment]
+1

**Comment by fvisticot** [comment]
I have tried to use the FirebaseConnector on iOS to get the Firebase token:

```
_firebasePushConnector.configure();
    _firebasePushConnector.token.addListener(() {
      print(_firebasePushConnector.token.value);
    });
```

But I get an error:

 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      FirebaseMessaging.configure (package:firebase_messaging/firebase_messaging.dart:114:14)
#3      FirebasePushConnector.configure (package:flutter_apns/firebase_connector.dart:13:15)

**Comment by phamotcreations** [comment]
+1

Unable to get firebase token on android

**Comment by szotp** [comment]
The point of this library is to not setup firebase, that's why it won't work. If you don't mind firebase, then just use it, and then add handling for this method:

https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application

(don't forget to call super, otherwise firebase won't work)

you won't need this package at all
