### ISSUE TITLE
Upgrade to null safety

### ISSUE THREAD

**Issue by sachin052** [mwaylabs/flutter-apns#48]

**Comment by andzejsw** [comment]
Because firebase_messaging >=7.0.0 <7.0.3 depends on firebase_core ^0.5.0 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging >=7.0.0 <7.0.3-∞ or >7.0.3 <8.0.0 requires firebase_core ^0.5.0.
And because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1, firebase_messaging ^7.0.0 requires firebase_core ^0.5.0.
Because no versions of flutter_apns match >1.4.1 <2.0.0 and flutter_apns 1.4.1 depends on firebase_messaging ^7.0.0, flutter_apns ^1.4.1 requires firebase_messaging ^7.0.0.
Thus, flutter_apns ^1.4.1 requires firebase_core ^0.5.0.
So, because smartmex depends on both flutter_apns ^1.4.1 and firebase_core ^1.0.1, version solving failed.
pub get failed (1; So, because smartmex depends on both flutter_apns ^1.4.1 and firebase_core ^1.0.1, version solving failed.)Because firebase_messaging >=7.0.0 <7.0.3 depends on firebase_core ^0.5.0 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging >=7.0.0 <7.0.3-∞ or >7.0.3 <8.0.0 requires firebase_core ^0.5.0.
And because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1, firebase_messaging ^7.0.0 requires firebase_core ^0.5.0.
Because no versions of flutter_apns match >1.4.1 <2.0.0 and flutter_apns 1.4.1 depends on firebase_messaging ^7.0.0, flutter_apns ^1.4.1 requires firebase_messaging ^7.0.0.
Thus, flutter_apns ^1.4.1 requires firebase_core ^0.5.0.
So, because smartmex depends on both flutter_apns ^1.4.1 and firebase_core ^1.0.1, version solving failed.
pub get failed (1; So, because smartmex depends on both flutter_apns ^1.4.1 and firebase_core ^1.0.1, version solving failed.)

**Comment by guopeng1994** [comment]
same problem

**Comment by andzejsw** [comment]
I have created 1.4.2 flutter-apns version with null safety from https://github.com/mohammedhasna2015/flutter-apns fork in my own fork: https://github.com/andzejsw/flutter-apns

@szotp Do you plan to implement those changes!?

**Comment by szotp** [comment]
@andzejsw hi, yes. Nice fork chain btw, I'll see if I can merge it.

**Comment by andzejsw** [comment]
> @andzejsw hi, yes. Nice fork chain btw, I'll see if I can merge it.

Should I create pull request?

**Comment by szotp** [comment]
No thanks, I just noticed that fork removed firebase_messaging so I need to merge certain commits only.

**Comment by guopeng1994** [comment]
nice job ~ @szotp @andzejsw

**Comment by andzejsw** [comment]
@szotp is required commits merged or not? And if yes, when you plan to submit changes in pub.dev?

**Comment by szotp** [comment]
I prepared a prerelease:
https://pub.dev/packages/flutter_apns/versions/1.5.0-dev.1
https://pub.dev/packages/flutter_apns_only

Let me know if that works for you. I suspect there may be some issues due to amount of changes in new version.

**Comment by szotp** [comment]
1.5.0 has been released
